name: Build and Release sitt CLI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            extension: ''
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos
            extension: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows
            extension: '.exe'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build CLI Binary
        run: |
          cargo build --release --target ${{ matrix.target }} --manifest-path cli/Cargo.toml

      - name: Copy Binary to bin Directory
        run: |
          mkdir -p bin
          cp target/${{ matrix.target }}/release/sitt${{ matrix.extension }} bin/sitt-${{ matrix.platform }}${{ matrix.extension }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
