name: Build CLI Binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            extension: ''
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos
            extension: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows
            extension: '.exe'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build CLI Binary
        run: |
          cargo build --release --target ${{ matrix.target }} --manifest-path cli/Cargo.toml

      - name: Copy Binary to bin Directory
        run: |
          mkdir -p bin/${{ matrix.platform }}
          cp target/${{ matrix.target }}/release/sitt${{ matrix.extension }} bin/${{ matrix.platform }}/sitt${{ matrix.extension }}

      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sitt-${{ matrix.platform }}
          path: bin/${{ matrix.platform }}/sitt${{ matrix.extension }}
